# handlers/main.yaml
- name: started_docker
  ansible.builtin.systemd:
    name: "{{ docker_service_name }}"
    state: started
    enabled: true

- name: restarted_docker
  ansible.builtin.systemd:
    name: "{{ docker_service_name }}"
    state: restarted
    enabled: true