# molecule/default/molecule.yml
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yaml

driver:
  name: docker

platforms:
  - name: ubuntu-jammy
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible:latest"
    command: /lib/systemd/systemd
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
